# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        args: ["--fix", "--extend-select", "N", "--extend-select", "ERA"]
        exclude: ^(backend/alembic/env\.py|backend/app/db/config\.py)$

        # add naming rules, remove commented code, unused import

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        # Targets frontend files specifically
        types_or: [javascript, jsx, ts, tsx, css, scss, html]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.1.1
    hooks:
      - id: eslint
        args: ["--config", "frontend/eslint.config.js"]
        files: \.[jt]sx?$  # Matches .js, .jsx, .ts, .tsx
        types: [file]
        additional_dependencies:
          - eslint@^9.0.0
          - eslint-plugin-react@latest
          - eslint-plugin-react-hooks@latest
          - eslint-plugin-react-refresh@latest
          - "@typescript-eslint/eslint-plugin@latest"
          - "@typescript-eslint/parser@latest"
          - globals@latest
          - "@eslint/js@latest"
