"""refine Inerview

Revision ID: 3b6c89c82a77
Revises: 6e0306461185
Create Date: 2025-12-31 14:05:28.223373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6c89c82a77'
down_revision: Union[str, Sequence[str], None] = '6e0306461185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_session_order', 'interview_interaction', ['session_id', 'order_index'], unique=False)
    op.create_unique_constraint('uq_session_order', 'interview_interaction', ['session_id', 'order_index'])
    op.drop_constraint(op.f('fk_interview_interaction_session_id_interview_session'), 'interview_interaction', type_='foreignkey')
    op.create_foreign_key(op.f('fk_interview_interaction_session_id_interview_session'), 'interview_interaction', 'interview_session', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_interview_interaction_session_id_interview_session'), 'interview_interaction', type_='foreignkey')
    op.create_foreign_key(op.f('fk_interview_interaction_session_id_interview_session'), 'interview_interaction', 'interview_session', ['session_id'], ['id'])
    op.drop_constraint('uq_session_order', 'interview_interaction', type_='unique')
    op.drop_index('ix_session_order', table_name='interview_interaction')
    # ### end Alembic commands ###
