"""initial_tables

Revision ID: 6e0306461185
Revises: 
Create Date: 2025-12-15 12:06:47.196787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0306461185'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('interview_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_interview_session_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_session'))
    )
    op.create_table('interview_interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_content', sa.Text(), nullable=False),
    sa.Column('reference_data', sa.JSON(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('user_answer_text', sa.Text(), nullable=True),
    sa.Column('user_audio_url', sa.String(), nullable=True),
    sa.Column('grade_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_session.id'], name=op.f('fk_interview_interaction_session_id_interview_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_interaction'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_interaction')
    op.drop_table('interview_session')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
