"""add max_id

Revision ID: d07a3e7c1c9f
Revises: d28fd22cc6fc
Create Date: 2025-12-31 19:09:13.698495

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d07a3e7c1c9f"
down_revision: Union[str, Sequence[str], None] = "d28fd22cc6fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interview_session", sa.Column("max_index", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interview_session", "max_index")
    # ### end Alembic commands ###
