"""delete full_name

Revision ID: d28fd22cc6fc
Revises: 09042b933a10
Create Date: 2025-12-31 17:42:53.436203

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d28fd22cc6fc"
down_revision: Union[str, Sequence[str], None] = "09042b933a10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
