"""add job_title

Revision ID: fae0df016849
Revises: d07a3e7c1c9f
Create Date: 2025-12-31 23:03:55.988452

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fae0df016849"
down_revision: Union[str, Sequence[str], None] = "d07a3e7c1c9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interview_session", sa.Column("job_title", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interview_session", "job_title")
    # ### end Alembic commands ###
